-- Tabla para NotificationType (Tipo de Notificación)
CREATE TABLE NotificationType (
                                  id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- ID autoincremental
                                  uuid UUID UNIQUE NOT NULL, -- UUID único
                                  description VARCHAR(255) NOT NULL,
                                  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                  active BOOLEAN DEFAULT true,
                                  CONSTRAINT NotificationType_pk PRIMARY KEY (id)
);

-- Tabla para NotificationTemplate (Plantilla de Notificación)
CREATE TABLE NotificationTemplate (
                                      id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- ID autoincremental
                                      uuid UUID UNIQUE NOT NULL, -- UUID único
                                      content TEXT NOT NULL,
                                      notification_type_id int8 REFERENCES NotificationType(id) ON DELETE CASCADE,
                                      priority INT DEFAULT 1, -- 1: low, 2: medium, 3: high
                                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                      active BOOLEAN DEFAULT true,
                                      CONSTRAINT NotificationTemplate_pk PRIMARY KEY (id)
);

-- Tabla para Notification (Notificación)
CREATE TABLE Notification (
                              id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- ID autoincremental
                              uuid UUID UNIQUE NOT NULL, -- UUID único
                              user_uuid UUID NOT NULL ,
                              send_date TIMESTAMP NOT NULL,
                              template_id INT REFERENCES NotificationTemplate(id) ON DELETE CASCADE,
                              status VARCHAR(50) DEFAULT 'pending', -- Ej: "pending", "sent", "failed"
                              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                              updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                              active BOOLEAN DEFAULT true,
                              CONSTRAINT Notification_pk PRIMARY KEY (id)
);